DefaultContentLanguage = "en"
baseURL = "https://not-a-boring-mary-anne.netlify.app/"
ignoreErrors = ["error-remote-getjson"]
languageCode = "en"
theme = "hugo.386"
title = "Not a Boring Mary Anne"
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1
[params]
copyrightname = "madi"
copyrighturl = "http://not-a-boring-mary-anne.netlify.app"
email = "mailto:masdimaisip@gmail.com"
github = "https://github.com/not-a-boring-mary-anne"
linkedin = "https://www.linkedin.com/in/not-a-boring-mary-anne/"
loadfastload = false
loadonepass = false
loadspeedfactor = 1.0
mainpagedesc = "This includes what I do and some of the coolest projects I'm working on."
mainpagesubtitle = "Welcome to my 90s throwback portfolio!"
mainpagetitle = "Not a Boring Mary Anne"
showhugo = false
[params.copyright]
name = "Mary Anne Dimaisip"
prefix = "[hugo.386 theme by Max le Fou](https://gitlab.com/maxlefou/hugo.386)"
suffix = "Example site"
url = "http://not-a-boring-mary-anne.netlify.app"
